### ISSUE TITLE
Docker Hub token in build secrets seems to have expired

### ISSUE THREAD

**Issue by wokket** [erikbra/grate#199]
@erikbra I took the liberty of pushing [a new release](https://github.com/erikbra/grate/releases/tag/1.3.0) today, however [the docker step of the build pipeline](https://github.com/erikbra/grate/runs/6787454578?check_suite_focus=true) has failed to connect to Docker Hub.

I rightfully don't have any access to the pipeline secrets, would you mind checking on this when you get a chance??  I don't use the docker image myself so I'm in no hurry.

Winget, dotnet global tool etc all worked just fine, and are available for immediate use 🥳

**Comment by erikbra** [comment]
Hi, @wokket . I saw that you pushed a release, and I really appreciate it! This is what open source is all about, cooperation :) and I know I haven't been super-active here lately, as I have had a lot of other stuff to do in other parts of my life (you know, life, work, etc 😆 )

I'll look into the docker token:)

**Comment by erikbra** [comment]
The docker hub token looks good, but the issue is probably due to using github.actor in the pipeline step, because that is probably not me when someone else has triggered the build:

<img width="521" alt="image" src="https://user-images.githubusercontent.com/1628994/172541213-f91160a8-ca79-44f0-b547-c40946747bf8.png">
https://github.com/erikbra/grate/blob/main/.github/workflows/build.yml#L174

I re-ran the build, and now it worked. It would make sense to replace github.actor here with a build environment variable instead, e.g:

```
username: ${{ env.DOCKER_HUB_USERNAME }}
```

**Comment by erikbra** [comment]
I created a new issue for the actual fix: https://github.com/erikbra/grate/issues/200
