### ISSUE TITLE
Winget package not updating after build

### ISSUE THREAD

**Issue by wokket** [erikbra/grate#209]
I've just pushed the updated 1.3.2 release, and was checking it had arrived on the various platforms, and noticed winget is still sitting on 1.2.0.

This means the two releases I've pushed haven't gone to winget.

We need to get the winget updates happening as part of the build, or add some docco explaining the release procedure so I know what to do 😄

**Comment by jwright-linq** [comment]
It appears winget manifests are in the `installers/winget/grate/manifests/e/erikbra/grate` directory.
In order to submit to the winget package repo, you should only need to do a couple steps.

1. Ensure [winget](https://github.com/microsoft/winget-cli) is installed on your machine.
2. install [wingetcreate](https://github.com/microsoft/winget-create) is installed.
3. update the manifest with the new version by running the Create-Installer.ps1 script: `installers/winget/Create-Installer.ps1`
    - When running that powershell script, you need to pass the new version. In a powershell window... `./grate-version.ps1 1.3.1`

I'm on a MacOS environment, so I can't test the creation of this new release for winget, but from Microsoft's documentation, and looking at the source, this is what I could piece together.

Also, see: https://github.com/erikbra/grate/issues/77 for additional information.

**Comment by erikbra** [comment]
We should be able to do this as part of the release pipeline now: https://github.com/microsoft/winget-create#using-windows-package-manager-manifest-creator-in-a-cicd-pipeline

We need a separate build step, which runs on a Windows agent, and does what's described in the link above

**Comment by erikbra** [comment]
Resolved with #231 

grate 1.4.0 is on its way out to winget: https://github.com/microsoft/winget-pkgs/pull/77881
