### ISSUE TITLE
Inconsistent script type for RunFirstAfterUpdate folder in documentation

### ISSUE THREAD

**Issue by BobLd** [erikbra/grate#355]
**Describe the bug**
`RunFirstAfterUpdate` folder is marked as an `Anytime` script folder in some part of the documentation (see [here](https://erikbra.github.io/grate/script-types/anytime/#folders)), and as a `One-time` script folder in other parts (see [here](https://erikbra.github.io/grate/folder-configuration/#default-folder-configuration)).

**Expected behavior**
From the code, I see it's a `One-time` script (see [here](https://github.com/erikbra/grate/blob/9a0b8826a5f02a343bd6fe837a68cd2966eb050b/grate/Configuration/FoldersConfiguration.cs#L43C13-L43C132)). The script type should be consistently marked as `One-time` accross the documentation. **As a side note it's worth mentionning that RoundHouse had the `RunFirstAfterUpdate` folder as an `Anytime` script folder (contrary to grate)**, so adding a note about the change would be very useful for people migrating (as it might be a breaking change)

**Comment by wokket** [comment]
Thanks for letting us know about this regression :)

AFAICT this has (incorrectly) been a `One-Time` folder in grate since we first started it, it's just taken until now for anyone to notice!  I suspect the discrepencies in docco come from where we've migrated the RH docs across vs those we've written alongside the code here.

Can anyone forsee any issues if we changed the folder to `Any-Time` to restore back-compat with RH?  To my mind anyone that's currently relying on it being `One-Time` won't have made any changes to their scripts once run, so suddenly making them _elegible_ for re-running if changed shouldn't be a big deal?

**Comment by erikbra** [comment]
I agree with you, @wokket, this is a bug in the implementation. And, it doesn't make sense to have the "run first after update" as a one-time script at all, imho. I don't understand how people would use it this way. I'm for changing the script type to Anytime.

Thanks for reporting, @BobLd !
