### ISSUE TITLE
Scripts in internal Grate migration tables are always registered as "run"

### ISSUE THREAD

**Issue by erikbra** [erikbra/grate#524]
**Describe the bug**
The internal Grate migration tables always logs all scripts. Might be due to line ending issues when reading from embedded resources, might now

**To Reproduce**
Run a migration, look at the grate.GrateScriptsRun table.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS, Linux]
 - Version: [e.g. 1.0.2]

**Additional context**

**Comment by dgeller-OUHSC** [comment]
@erikbra could that potentially related to a bug we've been seeing intermittently?

`Initializing connections.
Running grate v1.7.4 (build date 05/16/2024 01:50:03) against 127.0.0.1 - bam.
Looking in database\data for scripts to run.
================================================================================
Setup, Backup, Create/Restore/Drop
================================================================================
================================================================================
Grate Structure
================================================================================
An error occurred: Migration failed due to the following errors:
Update ("up"):
--------------------------------------------------------------------------------
grate-internal\02_create_scripts_run_table.sql: Table 'grate_GrateScriptsRun' already exists`

**Comment by drhamann** [comment]
I reproduce the same issue at the item [544](https://github.com/erikbra/grate/issues/544) will follow here if have any news.

**Comment by erikbra** [comment]
The issue is that the base tables migration is always run in baseline mode (i.e. always registered as run), if the scriptsrun, scriptsrunerrors and version tables already exist (which they do every time, after they are created the first time)
