### ISSUE TITLE
Create really small docker image - with usage examples

### ISSUE THREAD

**Issue by erikbra** [erikbra/grate#62]
Can use one of the self-contained binaries - no .NET needed on base images.

- [ ] Document how to work with volumes
- [ ] Document how to use in a k8s scenario(?)

**Comment by wokket** [comment]
Do we want to be responsible for maintaining a docker image (updating base dependencies, handling security updates etc) or is the example usage I'm doing for #41 enough to get started?

**Comment by wokket** [comment]
FYI I had a crack at starting this as part of #41 .  There's a few things that have made life more difficult than it should but there's something resembling a working sample coming when I PR that feature branch.  Main gotchas so far include:
- adding the globalisation libraries into Alpine so SQL can work (I have to do this for RH/my apps as well so no biggie)
- the global.json has to be ignored due to a framework mismatch between the file and the alpine image.

Current image size is about 75Mb.

**Comment by erikbra** [comment]
FYI: Docker image is now available on Docker hub:

https://hub.docker.com/r/erikbra/grate

**Comment by erikbra** [comment]
It should be possible to create a simple Dockerfile like this now:

```Dockerfile
FROM erikbra/grate:latest
COPY ./my_scripts ./db
ENTRYPOINT ./grate -f=db --connectionstring "$CONNECTIONSTRING"
```

and, then build and run it like this, provided you have your connection string in an environment variable, CONNECTIONSTRING, on the host.

```bash
 docker build -t my-db-image .
 docker run --rm -e CONNECTIONSTRING my-db-image
```

There seems to be a bug (#89), however, when creating the migrations folder in the container. I get the following:
```
Unhandled exception: System.IO.IOException: The file '/app/grate' already exists.
   at System.IO.FileSystem.CreateDirectory(String )
   at System.IO.Directory.CreateDirectory(String )
   at grate.Migration.GrateMigrator.CreateChangeDropFolder(String folder)
   at grate.Migration.GrateMigrator.Migrate()
   at grate.Commands.MigrateCommand.<>c__DisplayClass0_0.<<-ctor>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   (...)
```
